# This is a basic workflow to help you get started with Actions

name: CMST 385

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:

          echo test, and deploy your project.
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy

# More GitHub Actions for Azure: https://github.com/Azure/actions

 

#Change the name to match your course name

#Example name: Deploy HTML Files to AppService - COURSENAME

name: Deploy HTML Files to AppService - CMST385

on:

  push:

    branches:

      - main

jobs:

  build-and-deploy:

    runs-on: windows-latest

     steps:

    - uses: actions/checkout@main

    - name: Deploy to Azure Web App

      uses: azure/webapps-deploy@v1

      with:

      #Change the app-name to match what was provided to you in the publish settings file, this is in a naming convention of 'COURSENAME-STUDENTUID'

        app-name: 'CMST385-jthompson298'    

        slot-name: 'production'

      #Change the publish profile to match what you named your secret setup in GitHub, Example shown below

        publish-profile: ${{ secrets.AppServiceCMST385 }}
